services:
  ftp:
    image: anthonyx82/ftp_antoniomartin
    container_name: ftp
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - USERS=${USERS}
      - ADDRESS=${ADDRESS}
    volumes:
      - /raid0/ftpsv/ftp:/raid0/ftpsv/ftp
    restart: unless-stopped
