services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: unless-stopped
    networks:
      - web
      - internal
    expose:
      - "16686"

  jaeger-proxy:
    image: nginx:alpine
    container_name: jaeger-proxy
    restart: unless-stopped
    networks:
      - web
      - internal
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jaeger.rule=Host(`anthonyx82.ddns.net`) && PathPrefix(`/jaeger`)"
      - "traefik.http.routers.jaeger.entrypoints=websecure"
      - "traefik.http.routers.jaeger.tls.certresolver=myresolver"
      - "traefik.http.services.jaeger.loadbalancer.server.port=80"
      - "traefik.http.routers.jaeger.middlewares=jaeger-auth"
      - "traefik.http.middlewares.jaeger-auth.basicauth.users=${JAEGER_AUTH_USERPASS}"

networks:
  web:
    external: true
  internal:
    driver: bridge
