services:
  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: unless-stopped
    pid: "host"
    environment:
      - GLANCES_OPT=-w
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glances.rule=Host(`anthonyx82.ddns.net`) && PathPrefix(`/performance`)"
      - "traefik.http.routers.glances.entrypoints=websecure"
      - "traefik.http.routers.glances.tls.certresolver=myresolver"
      - "traefik.http.services.glances.loadbalancer.server.port=61208"
      - "traefik.http.middlewares.glances-stripprefix.stripprefix.prefixes=/performance"
      - "traefik.http.routers.glances.middlewares=glances-stripprefix,glances-auth"
      - "traefik.http.middlewares.glances-auth.basicauth.users=${GLANCES_AUTH_USERPASS}"

networks:
  web:
    external: true
