services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer1
    restart: always
    ports:
      - "8001:8000"
      - "9444:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  portainer_agent:
    image: portainer/agent:lts
    container_name: portainer_agent2
    restart: always
    ports:
      - "9002:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/raid0/BlackOpsDocker/portainer
      o: bind
