services:
  portainerOLD:
    image: portainer/portainer-ce:latest
    container_name: portainerOLD
    restart: always
    ports:
      - "127.0.0.1:9001:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: none
      device: /raid0/ftpsv/ftp/Docker/volumes/black_ops_docker_portainer_data
      o: bind
